# Generated by Django 4.1.7 on 2023-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='cidr_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CIDR前缀'),
        ),
    ]
