# Generated by Django 4.1.7 on 2023-03-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_server', '0002_alter_proxyserver_cidr_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxylist',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='proxylist',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='订单ID'),
        ),
        migrations.AddField(
            model_name='proxylist',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户ID'),
        ),
    ]
