# Generated by Django 4.1.7 on 2023-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_server', '0003_proxylist_expired_at_proxylist_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='proxylist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
