version: '3'
services:
  ngnix:
    container_name: nginx
    image: nginx:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/mentos_shop_backend/config/nginx/mentosproxy.conf:/etc/nginx/conf.d/mentosproxy.conf
      - /opt/mentos_shop_backend/config/nginx/cert:/etc/nginx/cert
    privileged: true
    networks:
      network:
        ipv4_address: 177.8.0.13
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.8.0.0/16'